name: slipreel

packages:
  - packages/**

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  analyze:
    exec: flutter analyze --no-fatal-infos
    description: Run flutter analyze in all packages (infos non-fatal)
    packageFilters:
      ignore:
        - "*example*"

  test:
    exec: flutter test
    description: Run tests in all packages
    packageFilters:
      ignore:
        - "*example*"
        - "screen_recorder_windows"

  clean:
    exec: flutter clean
    description: Clean all packages
